services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    container_name: logstash
    ports:
      - '5044:5044'
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
