name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "🎉 Welcome to our project! We're so glad you're here. Thank you for your issue submission."
        pr-message: "🌟 Thank you for your pull request! We appreciate your contribution to the project. Welcome aboard!"
